string action        # action string
string rope
string marker
string tar
---
bool success           # success flag
string message         # human-readable message
int32 info             # information flag