// Generated by gencpp from file uni_lace_msgs/UniLaceStepServiceRequest.msg
// DO NOT EDIT!


#ifndef UNI_LACE_MSGS_MESSAGE_UNILACESTEPSERVICEREQUEST_H
#define UNI_LACE_MSGS_MESSAGE_UNILACESTEPSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace uni_lace_msgs
{
template <class ContainerAllocator>
struct UniLaceStepServiceRequest_
{
  typedef UniLaceStepServiceRequest_<ContainerAllocator> Type;

  UniLaceStepServiceRequest_()
    : act()  {
    }
  UniLaceStepServiceRequest_(const ContainerAllocator& _alloc)
    : act(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _act_type;
  _act_type act;





  typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UniLaceStepServiceRequest_

typedef ::uni_lace_msgs::UniLaceStepServiceRequest_<std::allocator<void> > UniLaceStepServiceRequest;

typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceStepServiceRequest > UniLaceStepServiceRequestPtr;
typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceStepServiceRequest const> UniLaceStepServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator1> & lhs, const ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.act == rhs.act;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator1> & lhs, const ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uni_lace_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09db63d1b2a62392d56e43d16c36ff60";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09db63d1b2a62392ULL;
  static const uint64_t static_value2 = 0xd56e43d16c36ff60ULL;
};

template<class ContainerAllocator>
struct DataType< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uni_lace_msgs/UniLaceStepServiceRequest";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"std_msgs/String act\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.act);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UniLaceStepServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uni_lace_msgs::UniLaceStepServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "act: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.act);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNI_LACE_MSGS_MESSAGE_UNILACESTEPSERVICEREQUEST_H
