// Generated by gencpp from file uni_lace_msgs/UniLaceStepService.msg
// DO NOT EDIT!


#ifndef UNI_LACE_MSGS_MESSAGE_UNILACESTEPSERVICE_H
#define UNI_LACE_MSGS_MESSAGE_UNILACESTEPSERVICE_H

#include <ros/service_traits.h>


#include <uni_lace_msgs/UniLaceStepServiceRequest.h>
#include <uni_lace_msgs/UniLaceStepServiceResponse.h>


namespace uni_lace_msgs
{

struct UniLaceStepService
{

typedef UniLaceStepServiceRequest Request;
typedef UniLaceStepServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UniLaceStepService
} // namespace uni_lace_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uni_lace_msgs::UniLaceStepService > {
  static const char* value()
  {
    return "af9f61a907e31117188b236c02aaf4bd";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceStepService&) { return value(); }
};

template<>
struct DataType< ::uni_lace_msgs::UniLaceStepService > {
  static const char* value()
  {
    return "uni_lace_msgs/UniLaceStepService";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceStepService&) { return value(); }
};


// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceStepServiceRequest> should match
// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceStepService >
template<>
struct MD5Sum< ::uni_lace_msgs::UniLaceStepServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uni_lace_msgs::UniLaceStepService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceStepServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uni_lace_msgs::UniLaceStepServiceRequest> should match
// service_traits::DataType< ::uni_lace_msgs::UniLaceStepService >
template<>
struct DataType< ::uni_lace_msgs::UniLaceStepServiceRequest>
{
  static const char* value()
  {
    return DataType< ::uni_lace_msgs::UniLaceStepService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceStepServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceStepServiceResponse> should match
// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceStepService >
template<>
struct MD5Sum< ::uni_lace_msgs::UniLaceStepServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uni_lace_msgs::UniLaceStepService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceStepServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uni_lace_msgs::UniLaceStepServiceResponse> should match
// service_traits::DataType< ::uni_lace_msgs::UniLaceStepService >
template<>
struct DataType< ::uni_lace_msgs::UniLaceStepServiceResponse>
{
  static const char* value()
  {
    return DataType< ::uni_lace_msgs::UniLaceStepService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceStepServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNI_LACE_MSGS_MESSAGE_UNILACESTEPSERVICE_H
