// Generated by gencpp from file uni_lace_msgs/UniLaceResetService.msg
// DO NOT EDIT!


#ifndef UNI_LACE_MSGS_MESSAGE_UNILACERESETSERVICE_H
#define UNI_LACE_MSGS_MESSAGE_UNILACERESETSERVICE_H

#include <ros/service_traits.h>


#include <uni_lace_msgs/UniLaceResetServiceRequest.h>
#include <uni_lace_msgs/UniLaceResetServiceResponse.h>


namespace uni_lace_msgs
{

struct UniLaceResetService
{

typedef UniLaceResetServiceRequest Request;
typedef UniLaceResetServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UniLaceResetService
} // namespace uni_lace_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uni_lace_msgs::UniLaceResetService > {
  static const char* value()
  {
    return "f4d24b83badf9180317ef840cefaa307";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceResetService&) { return value(); }
};

template<>
struct DataType< ::uni_lace_msgs::UniLaceResetService > {
  static const char* value()
  {
    return "uni_lace_msgs/UniLaceResetService";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceResetService&) { return value(); }
};


// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceResetServiceRequest> should match
// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceResetService >
template<>
struct MD5Sum< ::uni_lace_msgs::UniLaceResetServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uni_lace_msgs::UniLaceResetService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceResetServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uni_lace_msgs::UniLaceResetServiceRequest> should match
// service_traits::DataType< ::uni_lace_msgs::UniLaceResetService >
template<>
struct DataType< ::uni_lace_msgs::UniLaceResetServiceRequest>
{
  static const char* value()
  {
    return DataType< ::uni_lace_msgs::UniLaceResetService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceResetServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceResetServiceResponse> should match
// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceResetService >
template<>
struct MD5Sum< ::uni_lace_msgs::UniLaceResetServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uni_lace_msgs::UniLaceResetService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceResetServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uni_lace_msgs::UniLaceResetServiceResponse> should match
// service_traits::DataType< ::uni_lace_msgs::UniLaceResetService >
template<>
struct DataType< ::uni_lace_msgs::UniLaceResetServiceResponse>
{
  static const char* value()
  {
    return DataType< ::uni_lace_msgs::UniLaceResetService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceResetServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNI_LACE_MSGS_MESSAGE_UNILACERESETSERVICE_H
