// Generated by gencpp from file uni_lace_msgs/UniLaceInfoService.msg
// DO NOT EDIT!


#ifndef UNI_LACE_MSGS_MESSAGE_UNILACEINFOSERVICE_H
#define UNI_LACE_MSGS_MESSAGE_UNILACEINFOSERVICE_H

#include <ros/service_traits.h>


#include <uni_lace_msgs/UniLaceInfoServiceRequest.h>
#include <uni_lace_msgs/UniLaceInfoServiceResponse.h>


namespace uni_lace_msgs
{

struct UniLaceInfoService
{

typedef UniLaceInfoServiceRequest Request;
typedef UniLaceInfoServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UniLaceInfoService
} // namespace uni_lace_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uni_lace_msgs::UniLaceInfoService > {
  static const char* value()
  {
    return "3a92e7221553a608fa193b6ae18fdde5";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceInfoService&) { return value(); }
};

template<>
struct DataType< ::uni_lace_msgs::UniLaceInfoService > {
  static const char* value()
  {
    return "uni_lace_msgs/UniLaceInfoService";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceInfoService&) { return value(); }
};


// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceInfoServiceRequest> should match
// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceInfoService >
template<>
struct MD5Sum< ::uni_lace_msgs::UniLaceInfoServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uni_lace_msgs::UniLaceInfoService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceInfoServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uni_lace_msgs::UniLaceInfoServiceRequest> should match
// service_traits::DataType< ::uni_lace_msgs::UniLaceInfoService >
template<>
struct DataType< ::uni_lace_msgs::UniLaceInfoServiceRequest>
{
  static const char* value()
  {
    return DataType< ::uni_lace_msgs::UniLaceInfoService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceInfoServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceInfoServiceResponse> should match
// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceInfoService >
template<>
struct MD5Sum< ::uni_lace_msgs::UniLaceInfoServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uni_lace_msgs::UniLaceInfoService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceInfoServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uni_lace_msgs::UniLaceInfoServiceResponse> should match
// service_traits::DataType< ::uni_lace_msgs::UniLaceInfoService >
template<>
struct DataType< ::uni_lace_msgs::UniLaceInfoServiceResponse>
{
  static const char* value()
  {
    return DataType< ::uni_lace_msgs::UniLaceInfoService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceInfoServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNI_LACE_MSGS_MESSAGE_UNILACEINFOSERVICE_H
