// Generated by gencpp from file uni_lace_msgs/UniLaceInfoServiceResponse.msg
// DO NOT EDIT!


#ifndef UNI_LACE_MSGS_MESSAGE_UNILACEINFOSERVICERESPONSE_H
#define UNI_LACE_MSGS_MESSAGE_UNILACEINFOSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace uni_lace_msgs
{
template <class ContainerAllocator>
struct UniLaceInfoServiceResponse_
{
  typedef UniLaceInfoServiceResponse_<ContainerAllocator> Type;

  UniLaceInfoServiceResponse_()
    : info()  {
    }
  UniLaceInfoServiceResponse_(const ContainerAllocator& _alloc)
    : info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UniLaceInfoServiceResponse_

typedef ::uni_lace_msgs::UniLaceInfoServiceResponse_<std::allocator<void> > UniLaceInfoServiceResponse;

typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceInfoServiceResponse > UniLaceInfoServiceResponsePtr;
typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceInfoServiceResponse const> UniLaceInfoServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator1> & lhs, const ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator1> & lhs, const ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uni_lace_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12a155e3803bd9637acdd5f5509da193";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12a155e3803bd963ULL;
  static const uint64_t static_value2 = 0x7acdd5f5509da193ULL;
};

template<class ContainerAllocator>
struct DataType< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uni_lace_msgs/UniLaceInfoServiceResponse";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#response\n"
"std_msgs/String info\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UniLaceInfoServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uni_lace_msgs::UniLaceInfoServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "info: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNI_LACE_MSGS_MESSAGE_UNILACEINFOSERVICERESPONSE_H
