// Generated by gencpp from file uni_lace_msgs/UniLaceParamServiceResponse.msg
// DO NOT EDIT!


#ifndef UNI_LACE_MSGS_MESSAGE_UNILACEPARAMSERVICERESPONSE_H
#define UNI_LACE_MSGS_MESSAGE_UNILACEPARAMSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace uni_lace_msgs
{
template <class ContainerAllocator>
struct UniLaceParamServiceResponse_
{
  typedef UniLaceParamServiceResponse_<ContainerAllocator> Type;

  UniLaceParamServiceResponse_()
    : params_json()  {
    }
  UniLaceParamServiceResponse_(const ContainerAllocator& _alloc)
    : params_json(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _params_json_type;
  _params_json_type params_json;





  typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UniLaceParamServiceResponse_

typedef ::uni_lace_msgs::UniLaceParamServiceResponse_<std::allocator<void> > UniLaceParamServiceResponse;

typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceParamServiceResponse > UniLaceParamServiceResponsePtr;
typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceParamServiceResponse const> UniLaceParamServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator1> & lhs, const ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.params_json == rhs.params_json;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator1> & lhs, const ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uni_lace_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd5debcaac10dc60355cf969fc28100a";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd5debcaac10dc60ULL;
  static const uint64_t static_value2 = 0x355cf969fc28100aULL;
};

template<class ContainerAllocator>
struct DataType< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uni_lace_msgs/UniLaceParamServiceResponse";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#response\n"
"std_msgs/String params_json\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.params_json);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UniLaceParamServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uni_lace_msgs::UniLaceParamServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "params_json: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.params_json);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNI_LACE_MSGS_MESSAGE_UNILACEPARAMSERVICERESPONSE_H
