// Generated by gencpp from file uni_lace_msgs/UniLaceResetServiceRequest.msg
// DO NOT EDIT!


#ifndef UNI_LACE_MSGS_MESSAGE_UNILACERESETSERVICEREQUEST_H
#define UNI_LACE_MSGS_MESSAGE_UNILACERESETSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace uni_lace_msgs
{
template <class ContainerAllocator>
struct UniLaceResetServiceRequest_
{
  typedef UniLaceResetServiceRequest_<ContainerAllocator> Type;

  UniLaceResetServiceRequest_()
    : params()  {
    }
  UniLaceResetServiceRequest_(const ContainerAllocator& _alloc)
    : params(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _params_type;
  _params_type params;





  typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UniLaceResetServiceRequest_

typedef ::uni_lace_msgs::UniLaceResetServiceRequest_<std::allocator<void> > UniLaceResetServiceRequest;

typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceResetServiceRequest > UniLaceResetServiceRequestPtr;
typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceResetServiceRequest const> UniLaceResetServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator1> & lhs, const ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.params == rhs.params;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator1> & lhs, const ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uni_lace_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef1d9c3914312668d3583857dc8ec01f";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef1d9c3914312668ULL;
  static const uint64_t static_value2 = 0xd3583857dc8ec01fULL;
};

template<class ContainerAllocator>
struct DataType< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uni_lace_msgs/UniLaceResetServiceRequest";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"std_msgs/String params\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UniLaceResetServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uni_lace_msgs::UniLaceResetServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "params: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.params);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNI_LACE_MSGS_MESSAGE_UNILACERESETSERVICEREQUEST_H
