// Generated by gencpp from file uni_lace_msgs/UniLaceParamService.msg
// DO NOT EDIT!


#ifndef UNI_LACE_MSGS_MESSAGE_UNILACEPARAMSERVICE_H
#define UNI_LACE_MSGS_MESSAGE_UNILACEPARAMSERVICE_H

#include <ros/service_traits.h>


#include <uni_lace_msgs/UniLaceParamServiceRequest.h>
#include <uni_lace_msgs/UniLaceParamServiceResponse.h>


namespace uni_lace_msgs
{

struct UniLaceParamService
{

typedef UniLaceParamServiceRequest Request;
typedef UniLaceParamServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UniLaceParamService
} // namespace uni_lace_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uni_lace_msgs::UniLaceParamService > {
  static const char* value()
  {
    return "dd5debcaac10dc60355cf969fc28100a";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceParamService&) { return value(); }
};

template<>
struct DataType< ::uni_lace_msgs::UniLaceParamService > {
  static const char* value()
  {
    return "uni_lace_msgs/UniLaceParamService";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceParamService&) { return value(); }
};


// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceParamServiceRequest> should match
// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceParamService >
template<>
struct MD5Sum< ::uni_lace_msgs::UniLaceParamServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uni_lace_msgs::UniLaceParamService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceParamServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uni_lace_msgs::UniLaceParamServiceRequest> should match
// service_traits::DataType< ::uni_lace_msgs::UniLaceParamService >
template<>
struct DataType< ::uni_lace_msgs::UniLaceParamServiceRequest>
{
  static const char* value()
  {
    return DataType< ::uni_lace_msgs::UniLaceParamService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceParamServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceParamServiceResponse> should match
// service_traits::MD5Sum< ::uni_lace_msgs::UniLaceParamService >
template<>
struct MD5Sum< ::uni_lace_msgs::UniLaceParamServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uni_lace_msgs::UniLaceParamService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceParamServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uni_lace_msgs::UniLaceParamServiceResponse> should match
// service_traits::DataType< ::uni_lace_msgs::UniLaceParamService >
template<>
struct DataType< ::uni_lace_msgs::UniLaceParamServiceResponse>
{
  static const char* value()
  {
    return DataType< ::uni_lace_msgs::UniLaceParamService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UniLaceParamServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNI_LACE_MSGS_MESSAGE_UNILACEPARAMSERVICE_H
