// Generated by gencpp from file uni_lace_msgs/UniLaceStepServiceResponse.msg
// DO NOT EDIT!


#ifndef UNI_LACE_MSGS_MESSAGE_UNILACESTEPSERVICERESPONSE_H
#define UNI_LACE_MSGS_MESSAGE_UNILACESTEPSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <std_msgs/UInt8MultiArray.h>

namespace uni_lace_msgs
{
template <class ContainerAllocator>
struct UniLaceStepServiceResponse_
{
  typedef UniLaceStepServiceResponse_<ContainerAllocator> Type;

  UniLaceStepServiceResponse_()
    : obs()
    , obs_raw()  {
    }
  UniLaceStepServiceResponse_(const ContainerAllocator& _alloc)
    : obs(_alloc)
    , obs_raw(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _obs_type;
  _obs_type obs;

   typedef  ::std_msgs::UInt8MultiArray_<ContainerAllocator>  _obs_raw_type;
  _obs_raw_type obs_raw;





  typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UniLaceStepServiceResponse_

typedef ::uni_lace_msgs::UniLaceStepServiceResponse_<std::allocator<void> > UniLaceStepServiceResponse;

typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceStepServiceResponse > UniLaceStepServiceResponsePtr;
typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceStepServiceResponse const> UniLaceStepServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator1> & lhs, const ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.obs == rhs.obs &&
    lhs.obs_raw == rhs.obs_raw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator1> & lhs, const ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uni_lace_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d213a8c9c9c20d75e8f685fc69fa73a6";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd213a8c9c9c20d75ULL;
  static const uint64_t static_value2 = 0xe8f685fc69fa73a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uni_lace_msgs/UniLaceStepServiceResponse";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#response\n"
"std_msgs/String obs\n"
"std_msgs/UInt8MultiArray obs_raw\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt8MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"uint8[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obs);
      stream.next(m.obs_raw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UniLaceStepServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uni_lace_msgs::UniLaceStepServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "obs: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.obs);
    s << indent << "obs_raw: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.obs_raw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNI_LACE_MSGS_MESSAGE_UNILACESTEPSERVICERESPONSE_H
