// Generated by gencpp from file uni_lace_msgs/UniLaceParamServiceRequest.msg
// DO NOT EDIT!


#ifndef UNI_LACE_MSGS_MESSAGE_UNILACEPARAMSERVICEREQUEST_H
#define UNI_LACE_MSGS_MESSAGE_UNILACEPARAMSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uni_lace_msgs
{
template <class ContainerAllocator>
struct UniLaceParamServiceRequest_
{
  typedef UniLaceParamServiceRequest_<ContainerAllocator> Type;

  UniLaceParamServiceRequest_()
    {
    }
  UniLaceParamServiceRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UniLaceParamServiceRequest_

typedef ::uni_lace_msgs::UniLaceParamServiceRequest_<std::allocator<void> > UniLaceParamServiceRequest;

typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceParamServiceRequest > UniLaceParamServiceRequestPtr;
typedef boost::shared_ptr< ::uni_lace_msgs::UniLaceParamServiceRequest const> UniLaceParamServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace uni_lace_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uni_lace_msgs/UniLaceParamServiceRequest";
  }

  static const char* value(const ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
;
  }

  static const char* value(const ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UniLaceParamServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::uni_lace_msgs::UniLaceParamServiceRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // UNI_LACE_MSGS_MESSAGE_UNILACEPARAMSERVICEREQUEST_H
