// Generated by gencpp from file uni_lace_msgs/UnityStateControllerServiceResponse.msg
// DO NOT EDIT!


#ifndef UNI_LACE_MSGS_MESSAGE_UNITYSTATECONTROLLERSERVICERESPONSE_H
#define UNI_LACE_MSGS_MESSAGE_UNITYSTATECONTROLLERSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace uni_lace_msgs
{
template <class ContainerAllocator>
struct UnityStateControllerServiceResponse_
{
  typedef UnityStateControllerServiceResponse_<ContainerAllocator> Type;

  UnityStateControllerServiceResponse_()
    : sim_pos()  {
    }
  UnityStateControllerServiceResponse_(const ContainerAllocator& _alloc)
    : sim_pos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _sim_pos_type;
  _sim_pos_type sim_pos;





  typedef boost::shared_ptr< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UnityStateControllerServiceResponse_

typedef ::uni_lace_msgs::UnityStateControllerServiceResponse_<std::allocator<void> > UnityStateControllerServiceResponse;

typedef boost::shared_ptr< ::uni_lace_msgs::UnityStateControllerServiceResponse > UnityStateControllerServiceResponsePtr;
typedef boost::shared_ptr< ::uni_lace_msgs::UnityStateControllerServiceResponse const> UnityStateControllerServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator1> & lhs, const ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sim_pos == rhs.sim_pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator1> & lhs, const ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uni_lace_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15d431186ba988ebc556e3c1bad087a5";
  }

  static const char* value(const ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15d431186ba988ebULL;
  static const uint64_t static_value2 = 0xc556e3c1bad087a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uni_lace_msgs/UnityStateControllerServiceResponse";
  }

  static const char* value(const ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#response\n"
"geometry_msgs/PoseArray sim_pos\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sim_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UnityStateControllerServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uni_lace_msgs::UnityStateControllerServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "sim_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.sim_pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNI_LACE_MSGS_MESSAGE_UNITYSTATECONTROLLERSERVICERESPONSE_H
