// Generated by gencpp from file uni_lace_msgs/UnityStateControllerService.msg
// DO NOT EDIT!


#ifndef UNI_LACE_MSGS_MESSAGE_UNITYSTATECONTROLLERSERVICE_H
#define UNI_LACE_MSGS_MESSAGE_UNITYSTATECONTROLLERSERVICE_H

#include <ros/service_traits.h>


#include <uni_lace_msgs/UnityStateControllerServiceRequest.h>
#include <uni_lace_msgs/UnityStateControllerServiceResponse.h>


namespace uni_lace_msgs
{

struct UnityStateControllerService
{

typedef UnityStateControllerServiceRequest Request;
typedef UnityStateControllerServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UnityStateControllerService
} // namespace uni_lace_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uni_lace_msgs::UnityStateControllerService > {
  static const char* value()
  {
    return "f41682cf3f385f5d1be3d8588334a602";
  }

  static const char* value(const ::uni_lace_msgs::UnityStateControllerService&) { return value(); }
};

template<>
struct DataType< ::uni_lace_msgs::UnityStateControllerService > {
  static const char* value()
  {
    return "uni_lace_msgs/UnityStateControllerService";
  }

  static const char* value(const ::uni_lace_msgs::UnityStateControllerService&) { return value(); }
};


// service_traits::MD5Sum< ::uni_lace_msgs::UnityStateControllerServiceRequest> should match
// service_traits::MD5Sum< ::uni_lace_msgs::UnityStateControllerService >
template<>
struct MD5Sum< ::uni_lace_msgs::UnityStateControllerServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uni_lace_msgs::UnityStateControllerService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UnityStateControllerServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uni_lace_msgs::UnityStateControllerServiceRequest> should match
// service_traits::DataType< ::uni_lace_msgs::UnityStateControllerService >
template<>
struct DataType< ::uni_lace_msgs::UnityStateControllerServiceRequest>
{
  static const char* value()
  {
    return DataType< ::uni_lace_msgs::UnityStateControllerService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UnityStateControllerServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uni_lace_msgs::UnityStateControllerServiceResponse> should match
// service_traits::MD5Sum< ::uni_lace_msgs::UnityStateControllerService >
template<>
struct MD5Sum< ::uni_lace_msgs::UnityStateControllerServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uni_lace_msgs::UnityStateControllerService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UnityStateControllerServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uni_lace_msgs::UnityStateControllerServiceResponse> should match
// service_traits::DataType< ::uni_lace_msgs::UnityStateControllerService >
template<>
struct DataType< ::uni_lace_msgs::UnityStateControllerServiceResponse>
{
  static const char* value()
  {
    return DataType< ::uni_lace_msgs::UnityStateControllerService >::value();
  }
  static const char* value(const ::uni_lace_msgs::UnityStateControllerServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNI_LACE_MSGS_MESSAGE_UNITYSTATECONTROLLERSERVICE_H
