(cl:defpackage sl_msgs-srv
  (:use )
  (:export
   "FINDPATTERNSERVICE"
   "<FINDPATTERNSERVICE-REQUEST>"
   "FINDPATTERNSERVICE-REQUEST"
   "<FINDPATTERNSERVICE-RESPONSE>"
   "FINDPATTERNSERVICE-RESPONSE"
   "FINDPLANSERVICE"
   "<FINDPLANSERVICE-REQUEST>"
   "FINDPLANSERVICE-REQUEST"
   "<FINDPLANSERVICE-RESPONSE>"
   "FINDPLANSERVICE-RESPONSE"
   "FINDTARGETSSERVICE"
   "<FINDTARGETSSERVICE-REQUEST>"
   "FINDTARGETSSERVICE-REQUEST"
   "<FINDTARGETSSERVICE-RESPONSE>"
   "FINDTARGETSSERVICE-RESPONSE"
  ))

