// Generated by gencpp from file sl_msgs/findPatternServiceResponse.msg
// DO NOT EDIT!


#ifndef SL_MSGS_MESSAGE_FINDPATTERNSERVICERESPONSE_H
#define SL_MSGS_MESSAGE_FINDPATTERNSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int8MultiArray.h>

namespace sl_msgs
{
template <class ContainerAllocator>
struct findPatternServiceResponse_
{
  typedef findPatternServiceResponse_<ContainerAllocator> Type;

  findPatternServiceResponse_()
    : pattern()  {
    }
  findPatternServiceResponse_(const ContainerAllocator& _alloc)
    : pattern(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int8MultiArray_<ContainerAllocator>  _pattern_type;
  _pattern_type pattern;





  typedef boost::shared_ptr< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct findPatternServiceResponse_

typedef ::sl_msgs::findPatternServiceResponse_<std::allocator<void> > findPatternServiceResponse;

typedef boost::shared_ptr< ::sl_msgs::findPatternServiceResponse > findPatternServiceResponsePtr;
typedef boost::shared_ptr< ::sl_msgs::findPatternServiceResponse const> findPatternServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sl_msgs::findPatternServiceResponse_<ContainerAllocator1> & lhs, const ::sl_msgs::findPatternServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pattern == rhs.pattern;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sl_msgs::findPatternServiceResponse_<ContainerAllocator1> & lhs, const ::sl_msgs::findPatternServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d04d855767d2a79195175a4127d4dd3e";
  }

  static const char* value(const ::sl_msgs::findPatternServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd04d855767d2a791ULL;
  static const uint64_t static_value2 = 0x95175a4127d4dd3eULL;
};

template<class ContainerAllocator>
struct DataType< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sl_msgs/findPatternServiceResponse";
  }

  static const char* value(const ::sl_msgs::findPatternServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int8MultiArray pattern\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int8MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int8[]            data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::sl_msgs::findPatternServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pattern);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct findPatternServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sl_msgs::findPatternServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sl_msgs::findPatternServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "pattern: ";
    s << std::endl;
    Printer< ::std_msgs::Int8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.pattern);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SL_MSGS_MESSAGE_FINDPATTERNSERVICERESPONSE_H
