// Generated by gencpp from file sl_msgs/findPlanServiceResponse.msg
// DO NOT EDIT!


#ifndef SL_MSGS_MESSAGE_FINDPLANSERVICERESPONSE_H
#define SL_MSGS_MESSAGE_FINDPLANSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace sl_msgs
{
template <class ContainerAllocator>
struct findPlanServiceResponse_
{
  typedef findPlanServiceResponse_<ContainerAllocator> Type;

  findPlanServiceResponse_()
    : plan()  {
    }
  findPlanServiceResponse_(const ContainerAllocator& _alloc)
    : plan(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _plan_type;
  _plan_type plan;





  typedef boost::shared_ptr< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct findPlanServiceResponse_

typedef ::sl_msgs::findPlanServiceResponse_<std::allocator<void> > findPlanServiceResponse;

typedef boost::shared_ptr< ::sl_msgs::findPlanServiceResponse > findPlanServiceResponsePtr;
typedef boost::shared_ptr< ::sl_msgs::findPlanServiceResponse const> findPlanServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sl_msgs::findPlanServiceResponse_<ContainerAllocator1> & lhs, const ::sl_msgs::findPlanServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.plan == rhs.plan;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sl_msgs::findPlanServiceResponse_<ContainerAllocator1> & lhs, const ::sl_msgs::findPlanServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19fe59c3be17f06323e121cfc2b5607e";
  }

  static const char* value(const ::sl_msgs::findPlanServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19fe59c3be17f063ULL;
  static const uint64_t static_value2 = 0x23e121cfc2b5607eULL;
};

template<class ContainerAllocator>
struct DataType< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sl_msgs/findPlanServiceResponse";
  }

  static const char* value(const ::sl_msgs::findPlanServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String plan\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::sl_msgs::findPlanServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct findPlanServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sl_msgs::findPlanServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sl_msgs::findPlanServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "plan: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.plan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SL_MSGS_MESSAGE_FINDPLANSERVICERESPONSE_H
