// Generated by gencpp from file sl_msgs/findPatternService.msg
// DO NOT EDIT!


#ifndef SL_MSGS_MESSAGE_FINDPATTERNSERVICE_H
#define SL_MSGS_MESSAGE_FINDPATTERNSERVICE_H

#include <ros/service_traits.h>


#include <sl_msgs/findPatternServiceRequest.h>
#include <sl_msgs/findPatternServiceResponse.h>


namespace sl_msgs
{

struct findPatternService
{

typedef findPatternServiceRequest Request;
typedef findPatternServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct findPatternService
} // namespace sl_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sl_msgs::findPatternService > {
  static const char* value()
  {
    return "145ffa40f05356208146cb6e34948f0c";
  }

  static const char* value(const ::sl_msgs::findPatternService&) { return value(); }
};

template<>
struct DataType< ::sl_msgs::findPatternService > {
  static const char* value()
  {
    return "sl_msgs/findPatternService";
  }

  static const char* value(const ::sl_msgs::findPatternService&) { return value(); }
};


// service_traits::MD5Sum< ::sl_msgs::findPatternServiceRequest> should match
// service_traits::MD5Sum< ::sl_msgs::findPatternService >
template<>
struct MD5Sum< ::sl_msgs::findPatternServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sl_msgs::findPatternService >::value();
  }
  static const char* value(const ::sl_msgs::findPatternServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sl_msgs::findPatternServiceRequest> should match
// service_traits::DataType< ::sl_msgs::findPatternService >
template<>
struct DataType< ::sl_msgs::findPatternServiceRequest>
{
  static const char* value()
  {
    return DataType< ::sl_msgs::findPatternService >::value();
  }
  static const char* value(const ::sl_msgs::findPatternServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sl_msgs::findPatternServiceResponse> should match
// service_traits::MD5Sum< ::sl_msgs::findPatternService >
template<>
struct MD5Sum< ::sl_msgs::findPatternServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sl_msgs::findPatternService >::value();
  }
  static const char* value(const ::sl_msgs::findPatternServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sl_msgs::findPatternServiceResponse> should match
// service_traits::DataType< ::sl_msgs::findPatternService >
template<>
struct DataType< ::sl_msgs::findPatternServiceResponse>
{
  static const char* value()
  {
    return DataType< ::sl_msgs::findPatternService >::value();
  }
  static const char* value(const ::sl_msgs::findPatternServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SL_MSGS_MESSAGE_FINDPATTERNSERVICE_H
