// Generated by gencpp from file sl_msgs/findTargetsService.msg
// DO NOT EDIT!


#ifndef SL_MSGS_MESSAGE_FINDTARGETSSERVICE_H
#define SL_MSGS_MESSAGE_FINDTARGETSSERVICE_H

#include <ros/service_traits.h>


#include <sl_msgs/findTargetsServiceRequest.h>
#include <sl_msgs/findTargetsServiceResponse.h>


namespace sl_msgs
{

struct findTargetsService
{

typedef findTargetsServiceRequest Request;
typedef findTargetsServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct findTargetsService
} // namespace sl_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sl_msgs::findTargetsService > {
  static const char* value()
  {
    return "aa823e51a177fa5a87a4dc28394b4618";
  }

  static const char* value(const ::sl_msgs::findTargetsService&) { return value(); }
};

template<>
struct DataType< ::sl_msgs::findTargetsService > {
  static const char* value()
  {
    return "sl_msgs/findTargetsService";
  }

  static const char* value(const ::sl_msgs::findTargetsService&) { return value(); }
};


// service_traits::MD5Sum< ::sl_msgs::findTargetsServiceRequest> should match
// service_traits::MD5Sum< ::sl_msgs::findTargetsService >
template<>
struct MD5Sum< ::sl_msgs::findTargetsServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sl_msgs::findTargetsService >::value();
  }
  static const char* value(const ::sl_msgs::findTargetsServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sl_msgs::findTargetsServiceRequest> should match
// service_traits::DataType< ::sl_msgs::findTargetsService >
template<>
struct DataType< ::sl_msgs::findTargetsServiceRequest>
{
  static const char* value()
  {
    return DataType< ::sl_msgs::findTargetsService >::value();
  }
  static const char* value(const ::sl_msgs::findTargetsServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sl_msgs::findTargetsServiceResponse> should match
// service_traits::MD5Sum< ::sl_msgs::findTargetsService >
template<>
struct MD5Sum< ::sl_msgs::findTargetsServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sl_msgs::findTargetsService >::value();
  }
  static const char* value(const ::sl_msgs::findTargetsServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sl_msgs::findTargetsServiceResponse> should match
// service_traits::DataType< ::sl_msgs::findTargetsService >
template<>
struct DataType< ::sl_msgs::findTargetsServiceResponse>
{
  static const char* value()
  {
    return DataType< ::sl_msgs::findTargetsService >::value();
  }
  static const char* value(const ::sl_msgs::findTargetsServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SL_MSGS_MESSAGE_FINDTARGETSSERVICE_H
