// Generated by gencpp from file sl_msgs/findPlanServiceRequest.msg
// DO NOT EDIT!


#ifndef SL_MSGS_MESSAGE_FINDPLANSERVICEREQUEST_H
#define SL_MSGS_MESSAGE_FINDPLANSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int8MultiArray.h>
#include <std_msgs/Int8.h>

namespace sl_msgs
{
template <class ContainerAllocator>
struct findPlanServiceRequest_
{
  typedef findPlanServiceRequest_<ContainerAllocator> Type;

  findPlanServiceRequest_()
    : pattern()
    , aesthetic_mode()  {
    }
  findPlanServiceRequest_(const ContainerAllocator& _alloc)
    : pattern(_alloc)
    , aesthetic_mode(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int8MultiArray_<ContainerAllocator>  _pattern_type;
  _pattern_type pattern;

   typedef  ::std_msgs::Int8_<ContainerAllocator>  _aesthetic_mode_type;
  _aesthetic_mode_type aesthetic_mode;





  typedef boost::shared_ptr< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct findPlanServiceRequest_

typedef ::sl_msgs::findPlanServiceRequest_<std::allocator<void> > findPlanServiceRequest;

typedef boost::shared_ptr< ::sl_msgs::findPlanServiceRequest > findPlanServiceRequestPtr;
typedef boost::shared_ptr< ::sl_msgs::findPlanServiceRequest const> findPlanServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sl_msgs::findPlanServiceRequest_<ContainerAllocator1> & lhs, const ::sl_msgs::findPlanServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pattern == rhs.pattern &&
    lhs.aesthetic_mode == rhs.aesthetic_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sl_msgs::findPlanServiceRequest_<ContainerAllocator1> & lhs, const ::sl_msgs::findPlanServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "861f24e62833b3969ce584a7874c91a6";
  }

  static const char* value(const ::sl_msgs::findPlanServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x861f24e62833b396ULL;
  static const uint64_t static_value2 = 0x9ce584a7874c91a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sl_msgs/findPlanServiceRequest";
  }

  static const char* value(const ::sl_msgs::findPlanServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int8MultiArray pattern\n"
"std_msgs/Int8 aesthetic_mode\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int8MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int8[]            data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
"================================================================================\n"
"MSG: std_msgs/Int8\n"
"int8 data\n"
;
  }

  static const char* value(const ::sl_msgs::findPlanServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pattern);
      stream.next(m.aesthetic_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct findPlanServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sl_msgs::findPlanServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sl_msgs::findPlanServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "pattern: ";
    s << std::endl;
    Printer< ::std_msgs::Int8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.pattern);
    s << indent << "aesthetic_mode: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.aesthetic_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SL_MSGS_MESSAGE_FINDPLANSERVICEREQUEST_H
