// Generated by gencpp from file sl_msgs/findTargetsServiceResponse.msg
// DO NOT EDIT!


#ifndef SL_MSGS_MESSAGE_FINDTARGETSSERVICERESPONSE_H
#define SL_MSGS_MESSAGE_FINDTARGETSSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>
#include <std_msgs/Float64MultiArray.h>

namespace sl_msgs
{
template <class ContainerAllocator>
struct findTargetsServiceResponse_
{
  typedef findTargetsServiceResponse_<ContainerAllocator> Type;

  findTargetsServiceResponse_()
    : target()
    , confidence()  {
    }
  findTargetsServiceResponse_(const ContainerAllocator& _alloc)
    : target(_alloc)
    , confidence(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _target_type;
  _target_type target;

   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct findTargetsServiceResponse_

typedef ::sl_msgs::findTargetsServiceResponse_<std::allocator<void> > findTargetsServiceResponse;

typedef boost::shared_ptr< ::sl_msgs::findTargetsServiceResponse > findTargetsServiceResponsePtr;
typedef boost::shared_ptr< ::sl_msgs::findTargetsServiceResponse const> findTargetsServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator1> & lhs, const ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.target == rhs.target &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator1> & lhs, const ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7a55884040f67b420badbb3788ad1f3";
  }

  static const char* value(const ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7a55884040f67b4ULL;
  static const uint64_t static_value2 = 0x20badbb3788ad1f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sl_msgs/findTargetsServiceResponse";
  }

  static const char* value(const ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseArray target\n"
"std_msgs/Float64MultiArray confidence\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float64[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct findTargetsServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sl_msgs::findTargetsServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "target: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.target);
    s << indent << "confidence: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SL_MSGS_MESSAGE_FINDTARGETSSERVICERESPONSE_H
