// Generated by gencpp from file sl_msgs/findPlanService.msg
// DO NOT EDIT!


#ifndef SL_MSGS_MESSAGE_FINDPLANSERVICE_H
#define SL_MSGS_MESSAGE_FINDPLANSERVICE_H

#include <ros/service_traits.h>


#include <sl_msgs/findPlanServiceRequest.h>
#include <sl_msgs/findPlanServiceResponse.h>


namespace sl_msgs
{

struct findPlanService
{

typedef findPlanServiceRequest Request;
typedef findPlanServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct findPlanService
} // namespace sl_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sl_msgs::findPlanService > {
  static const char* value()
  {
    return "e752f9c85170cb73cc8cf790042cfd2d";
  }

  static const char* value(const ::sl_msgs::findPlanService&) { return value(); }
};

template<>
struct DataType< ::sl_msgs::findPlanService > {
  static const char* value()
  {
    return "sl_msgs/findPlanService";
  }

  static const char* value(const ::sl_msgs::findPlanService&) { return value(); }
};


// service_traits::MD5Sum< ::sl_msgs::findPlanServiceRequest> should match
// service_traits::MD5Sum< ::sl_msgs::findPlanService >
template<>
struct MD5Sum< ::sl_msgs::findPlanServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sl_msgs::findPlanService >::value();
  }
  static const char* value(const ::sl_msgs::findPlanServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sl_msgs::findPlanServiceRequest> should match
// service_traits::DataType< ::sl_msgs::findPlanService >
template<>
struct DataType< ::sl_msgs::findPlanServiceRequest>
{
  static const char* value()
  {
    return DataType< ::sl_msgs::findPlanService >::value();
  }
  static const char* value(const ::sl_msgs::findPlanServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sl_msgs::findPlanServiceResponse> should match
// service_traits::MD5Sum< ::sl_msgs::findPlanService >
template<>
struct MD5Sum< ::sl_msgs::findPlanServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sl_msgs::findPlanService >::value();
  }
  static const char* value(const ::sl_msgs::findPlanServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sl_msgs::findPlanServiceResponse> should match
// service_traits::DataType< ::sl_msgs::findPlanService >
template<>
struct DataType< ::sl_msgs::findPlanServiceResponse>
{
  static const char* value()
  {
    return DataType< ::sl_msgs::findPlanService >::value();
  }
  static const char* value(const ::sl_msgs::findPlanServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SL_MSGS_MESSAGE_FINDPLANSERVICE_H
