// Generated by gencpp from file sl_msgs/findTargetsServiceRequest.msg
// DO NOT EDIT!


#ifndef SL_MSGS_MESSAGE_FINDTARGETSSERVICEREQUEST_H
#define SL_MSGS_MESSAGE_FINDTARGETSSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sl_msgs
{
template <class ContainerAllocator>
struct findTargetsServiceRequest_
{
  typedef findTargetsServiceRequest_<ContainerAllocator> Type;

  findTargetsServiceRequest_()
    : target_name()
    , camera_name()  {
    }
  findTargetsServiceRequest_(const ContainerAllocator& _alloc)
    : target_name(_alloc)
    , camera_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_name_type;
  _target_name_type target_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _camera_name_type;
  _camera_name_type camera_name;





  typedef boost::shared_ptr< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct findTargetsServiceRequest_

typedef ::sl_msgs::findTargetsServiceRequest_<std::allocator<void> > findTargetsServiceRequest;

typedef boost::shared_ptr< ::sl_msgs::findTargetsServiceRequest > findTargetsServiceRequestPtr;
typedef boost::shared_ptr< ::sl_msgs::findTargetsServiceRequest const> findTargetsServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator1> & lhs, const ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_name == rhs.target_name &&
    lhs.camera_name == rhs.camera_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator1> & lhs, const ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d96b2e8e607f84b35c5c85d0ebd92a53";
  }

  static const char* value(const ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd96b2e8e607f84b3ULL;
  static const uint64_t static_value2 = 0x5c5c85d0ebd92a53ULL;
};

template<class ContainerAllocator>
struct DataType< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sl_msgs/findTargetsServiceRequest";
  }

  static const char* value(const ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string target_name\n"
"string camera_name\n"
;
  }

  static const char* value(const ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_name);
      stream.next(m.camera_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct findTargetsServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sl_msgs::findTargetsServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "target_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target_name);
    s << indent << "camera_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.camera_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SL_MSGS_MESSAGE_FINDTARGETSSERVICEREQUEST_H
