// Generated by gencpp from file sl_msgs/findPatternServiceRequest.msg
// DO NOT EDIT!


#ifndef SL_MSGS_MESSAGE_FINDPATTERNSERVICEREQUEST_H
#define SL_MSGS_MESSAGE_FINDPATTERNSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int8.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32MultiArray.h>

namespace sl_msgs
{
template <class ContainerAllocator>
struct findPatternServiceRequest_
{
  typedef findPatternServiceRequest_<ContainerAllocator> Type;

  findPatternServiceRequest_()
    : num_eyelets()
    , shoelace_length()
    , eyelet_positions()  {
    }
  findPatternServiceRequest_(const ContainerAllocator& _alloc)
    : num_eyelets(_alloc)
    , shoelace_length(_alloc)
    , eyelet_positions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int8_<ContainerAllocator>  _num_eyelets_type;
  _num_eyelets_type num_eyelets;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _shoelace_length_type;
  _shoelace_length_type shoelace_length;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _eyelet_positions_type;
  _eyelet_positions_type eyelet_positions;





  typedef boost::shared_ptr< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct findPatternServiceRequest_

typedef ::sl_msgs::findPatternServiceRequest_<std::allocator<void> > findPatternServiceRequest;

typedef boost::shared_ptr< ::sl_msgs::findPatternServiceRequest > findPatternServiceRequestPtr;
typedef boost::shared_ptr< ::sl_msgs::findPatternServiceRequest const> findPatternServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sl_msgs::findPatternServiceRequest_<ContainerAllocator1> & lhs, const ::sl_msgs::findPatternServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num_eyelets == rhs.num_eyelets &&
    lhs.shoelace_length == rhs.shoelace_length &&
    lhs.eyelet_positions == rhs.eyelet_positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sl_msgs::findPatternServiceRequest_<ContainerAllocator1> & lhs, const ::sl_msgs::findPatternServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04424f9afefb944f67aec327d9aeeb55";
  }

  static const char* value(const ::sl_msgs::findPatternServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04424f9afefb944fULL;
  static const uint64_t static_value2 = 0x67aec327d9aeeb55ULL;
};

template<class ContainerAllocator>
struct DataType< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sl_msgs/findPatternServiceRequest";
  }

  static const char* value(const ::sl_msgs::findPatternServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int8 num_eyelets\n"
"std_msgs/Float32 shoelace_length\n"
"std_msgs/Float32MultiArray eyelet_positions\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int8\n"
"int8 data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::sl_msgs::findPatternServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_eyelets);
      stream.next(m.shoelace_length);
      stream.next(m.eyelet_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct findPatternServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sl_msgs::findPatternServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sl_msgs::findPatternServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "num_eyelets: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.num_eyelets);
    s << indent << "shoelace_length: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.shoelace_length);
    s << indent << "eyelet_positions: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.eyelet_positions);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SL_MSGS_MESSAGE_FINDPATTERNSERVICEREQUEST_H
