robot_name: "yumi"

purple_lower:  [22, 0, 137]     
purple_upper: [255, 97, 255]
magenta_lower: [162,0,0]     
magenta_upper: [212, 102, 0]
red_lower:     [213, 62, 0]  
red_upper: [250, 113, 0]
pink_lower:    [237, 105, 0]    
pink_upper: [255, 189, 0]
cyan_lower:    [0, 175, 100]    
cyan_upper: [0, 130, 170]
grey_lower:    [108, 128, 67]   
grey_upper: [162, 150, 165]
yellow_lower:  [0, 186, 0]    
yellow_upper: [255, 255, 11]
